words:
- 'yes'
- 'no'
- like
- finish
- happy
- nice
- eat
- teacher
- sit
- deaf
- test
data_path: D:\Projects\Sign_language_collector\yes
camera_id: 0
video_size:
- 1600
- 900
fps: 30
frames_per_vid: 40
videos_per_word: 10
